#DUBBO
dubbox:
  application:
    name: xbin-store-web-portal
    organization: dubbox
    owner: binux
  registry:
    protocol: zookeeper
    address: zookeeper:2181
  annotation:
    package: cn.binux.portal.controller
  monitor:
    enabled: false
    address: apphost:6060
    username: admin
    password: admin



#logging:
#  level:
#    root: DEBUG
#  org:
#    springframework:
#      web: DEBUG


#配置模板想到classpath路径，后面须加上"/"
beetl:
  templates-path: templates/
  config:
      html-tag-flag: true
#配置模板的后缀，自动读取spring.mvc.view.suffix
spring:
  mvc:
    view:
      suffix: .html

server:
  port: 8101


# swagger2
swagger2.package: cn.binux.portal.controller

# 广告Cid
big_ad_index: 1


